<template>
    <div>
        <span>{{nownum}}</span>
        <span>{{type}}</span>
        <span>新增：{{newnum}}</span>
    </div>
</template>
<script>
export default({
    name:"MapTopShowCard",
    props:{
        nownum:{
            type:Number,
            required:true
        },
        type:{
            type:String,
            required:true
        },
        newnum:{
            type:Number,
            required:true
        }
    }
})
</script>
